version: '3.8' 

services:
  bookstore-api:
    build: .  # Build the image from the current directory (./)
    ports:
      - "80:80"  
    environment:
      MYSQL_HOST: 13.37.215.2
      MYSQL_USER: kenny  
      MYSQL_PASSWORD: 123456789  
      MYSQL_DB: bookstore_db 
    depends_on:
      - mysql  # Wait for the mysql service to be ready

  mysql:
    image: mysql:8.0  
    environment:
      MYSQL_ROOT_PASSWORD: 123456789  # Set the MySQL root password
      MYSQL_DATABASE: bookstore_db  

volumes:
  mysql-data:  
